language: node_js

# Supported node versions.
node_js:
  - "7"
  - "6"
  - "5"

# Yarn package caching.
cache:
  yarn: true
  directories:
    - "node_modules"

# Config for greenkeeper lock file update.
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

# Actual testing scritps.
script:
  - yarn run build
